#auto: true
encoding: utf-8

markdown: rdiscount
highlighter: pygments
gems: [jekyll-paginate]
paginate: 8
permalink: /:title

title: wenda's blog
url: http://isme.wang
feed: /atom.xml
author_info: <a href="http:/isme.wang/">Wenda</a>
